kind: pipeline
type: docker
name: Pull-Request

trigger:
  branch:
    - main
  event:
    exclude:
      - tag

steps:
  - name: unit-test
    image: public.ecr.aws/docker/library/golang:1.17
    commands:
      - go test ./...
    when:
      event:
        - pull_request

  - name: tag-and-release
    image: public.ecr.aws/docker/library/golang:1.17
    environment:
      GITHUB_TOKEN:
        from_secret: GITHUB_TOKEN
    commands:
      - ./scripts/ci/deploy.sh
    when:
      event:
        - push