aws_environment: &aws_environment
  AWS_ACCESS_KEY_ID:
    from_secret: AWS_ACCESS_KEY_ID
  AWS_SECRET_ACCESS_KEY:
    from_secret: AWS_SECRET_ACCESS_KEY
  AWS_DEFAULT_REGION: eu-west-1

kind: pipeline
type: docker
name: Pull-Request

trigger:
  branch:
    - main
  event:
    exclude:
      - tag

steps:
  - name: unit-test
    image: public.ecr.aws/docker/library/golang:1.17
    commands:
      - go test ./...
    when:
      event:
        - pull_request
